name: 'Fill Hilan by cron'
on:
  schedule:
    - cron: 0 8 * * 0,1,2,3,4
  workflow_dispatch:


jobs:
  fill-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci

      - name: Inject vars
        run: |
          touch .env
          echo HILAN_URL=${{ secrets.HILAN_URL }} >> .env
          echo HILAN_USER=${{ secrets.HILAN_USER }} >> .env
          echo HILAN_PASSWORD=${{ secrets.HILAN_PASSWORD }} >> .env

      - name: Run Cypress
        run: npm start
